<?xml version="1.0" encoding="utf-8"?><Database Name="FBM_Database" Class="L2SQL_FBMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\FBM_Database.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="ROL_FoodBankManager.Properties.Settings" SettingsPropertyName="FBM_DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bin" Member="Bins">
    <Type Name="Bin">
      <Column Name="Bin_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Shelf_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Row_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FoodItem" Member="FoodItems">
    <Type Name="FoodItem">
      <Column Name="UPC" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Food_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Food_Group" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Food_Item" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Min_Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Personal_Care_Item" Member="Personal_Care_Items">
    <Type Name="Personal_Care_Item">
      <Column Name="UPC" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Item_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Warehouse" Member="Warehouses">
    <Type Name="Warehouse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shelf_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Row_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>