#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROL_FoodBankManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FBM_Database")]
	public partial class L2SQL_FBMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBin(Bin instance);
    partial void UpdateBin(Bin instance);
    partial void DeleteBin(Bin instance);
    partial void InsertFoodItem(FoodItem instance);
    partial void UpdateFoodItem(FoodItem instance);
    partial void DeleteFoodItem(FoodItem instance);
    partial void InsertPersonal_Care_Item(Personal_Care_Item instance);
    partial void UpdatePersonal_Care_Item(Personal_Care_Item instance);
    partial void DeletePersonal_Care_Item(Personal_Care_Item instance);
    partial void InsertWarehouse(Warehouse instance);
    partial void UpdateWarehouse(Warehouse instance);
    partial void DeleteWarehouse(Warehouse instance);
    #endregion
		
		public L2SQL_FBMDataContext() : 
				base(global::ROL_FoodBankManager.Properties.Settings.Default.FBM_DatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public L2SQL_FBMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public L2SQL_FBMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public L2SQL_FBMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public L2SQL_FBMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bin> Bins
		{
			get
			{
				return this.GetTable<Bin>();
			}
		}
		
		public System.Data.Linq.Table<FoodItem> FoodItems
		{
			get
			{
				return this.GetTable<FoodItem>();
			}
		}
		
		public System.Data.Linq.Table<Personal_Care_Item> Personal_Care_Items
		{
			get
			{
				return this.GetTable<Personal_Care_Item>();
			}
		}
		
		public System.Data.Linq.Table<Warehouse> Warehouses
		{
			get
			{
				return this.GetTable<Warehouse>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bin")]
	public partial class Bin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Bin_Id;
		
		private string _Category;
		
		private int _Shelf_Id;
		
		private int _Row_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBin_IdChanging(int value);
    partial void OnBin_IdChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnShelf_IdChanging(int value);
    partial void OnShelf_IdChanged();
    partial void OnRow_IdChanging(int value);
    partial void OnRow_IdChanged();
    #endregion
		
		public Bin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bin_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Bin_Id
		{
			get
			{
				return this._Bin_Id;
			}
			set
			{
				if ((this._Bin_Id != value))
				{
					this.OnBin_IdChanging(value);
					this.SendPropertyChanging();
					this._Bin_Id = value;
					this.SendPropertyChanged("Bin_Id");
					this.OnBin_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shelf_Id", DbType="Int NOT NULL")]
		public int Shelf_Id
		{
			get
			{
				return this._Shelf_Id;
			}
			set
			{
				if ((this._Shelf_Id != value))
				{
					this.OnShelf_IdChanging(value);
					this.SendPropertyChanging();
					this._Shelf_Id = value;
					this.SendPropertyChanged("Shelf_Id");
					this.OnShelf_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Row_Id", DbType="Int NOT NULL")]
		public int Row_Id
		{
			get
			{
				return this._Row_Id;
			}
			set
			{
				if ((this._Row_Id != value))
				{
					this.OnRow_IdChanging(value);
					this.SendPropertyChanging();
					this._Row_Id = value;
					this.SendPropertyChanged("Row_Id");
					this.OnRow_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FoodItem")]
	public partial class FoodItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UPC;
		
		private string _Food_Name;
		
		private int _Quantity;
		
		private string _Food_Group;
		
		private string _Food_Item;
		
		private int _Min_Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUPCChanging(string value);
    partial void OnUPCChanged();
    partial void OnFood_NameChanging(string value);
    partial void OnFood_NameChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnFood_GroupChanging(string value);
    partial void OnFood_GroupChanged();
    partial void OnFood_ItemChanging(string value);
    partial void OnFood_ItemChanged();
    partial void OnMin_ValueChanging(int value);
    partial void OnMin_ValueChanged();
    #endregion
		
		public FoodItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPC", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UPC
		{
			get
			{
				return this._UPC;
			}
			set
			{
				if ((this._UPC != value))
				{
					this.OnUPCChanging(value);
					this.SendPropertyChanging();
					this._UPC = value;
					this.SendPropertyChanged("UPC");
					this.OnUPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Name", DbType="VarChar(50)")]
		public string Food_Name
		{
			get
			{
				return this._Food_Name;
			}
			set
			{
				if ((this._Food_Name != value))
				{
					this.OnFood_NameChanging(value);
					this.SendPropertyChanging();
					this._Food_Name = value;
					this.SendPropertyChanged("Food_Name");
					this.OnFood_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Group", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Food_Group
		{
			get
			{
				return this._Food_Group;
			}
			set
			{
				if ((this._Food_Group != value))
				{
					this.OnFood_GroupChanging(value);
					this.SendPropertyChanging();
					this._Food_Group = value;
					this.SendPropertyChanged("Food_Group");
					this.OnFood_GroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Item", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Food_Item
		{
			get
			{
				return this._Food_Item;
			}
			set
			{
				if ((this._Food_Item != value))
				{
					this.OnFood_ItemChanging(value);
					this.SendPropertyChanging();
					this._Food_Item = value;
					this.SendPropertyChanged("Food_Item");
					this.OnFood_ItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Min_Value", DbType="Int NOT NULL")]
		public int Min_Value
		{
			get
			{
				return this._Min_Value;
			}
			set
			{
				if ((this._Min_Value != value))
				{
					this.OnMin_ValueChanging(value);
					this.SendPropertyChanging();
					this._Min_Value = value;
					this.SendPropertyChanged("Min_Value");
					this.OnMin_ValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personal_Care_Item")]
	public partial class Personal_Care_Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UPC;
		
		private string _Item_Type;
		
		private int _Quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUPCChanging(string value);
    partial void OnUPCChanged();
    partial void OnItem_TypeChanging(string value);
    partial void OnItem_TypeChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    #endregion
		
		public Personal_Care_Item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPC", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UPC
		{
			get
			{
				return this._UPC;
			}
			set
			{
				if ((this._UPC != value))
				{
					this.OnUPCChanging(value);
					this.SendPropertyChanging();
					this._UPC = value;
					this.SendPropertyChanged("UPC");
					this.OnUPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Item_Type
		{
			get
			{
				return this._Item_Type;
			}
			set
			{
				if ((this._Item_Type != value))
				{
					this.OnItem_TypeChanging(value);
					this.SendPropertyChanging();
					this._Item_Type = value;
					this.SendPropertyChanged("Item_Type");
					this.OnItem_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Warehouse")]
	public partial class Warehouse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Shelf_Id;
		
		private int _Row_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnShelf_IdChanging(int value);
    partial void OnShelf_IdChanged();
    partial void OnRow_IdChanging(int value);
    partial void OnRow_IdChanged();
    #endregion
		
		public Warehouse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shelf_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Shelf_Id
		{
			get
			{
				return this._Shelf_Id;
			}
			set
			{
				if ((this._Shelf_Id != value))
				{
					this.OnShelf_IdChanging(value);
					this.SendPropertyChanging();
					this._Shelf_Id = value;
					this.SendPropertyChanged("Shelf_Id");
					this.OnShelf_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Row_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Row_Id
		{
			get
			{
				return this._Row_Id;
			}
			set
			{
				if ((this._Row_Id != value))
				{
					this.OnRow_IdChanging(value);
					this.SendPropertyChanging();
					this._Row_Id = value;
					this.SendPropertyChanged("Row_Id");
					this.OnRow_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
